apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "name" . }}-config
spec:
  backendType: vault
  dataFrom:
  - secret/data/{{ template "environmentName" . }}/{{ template "name" . }}/config
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
