apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{ toYaml .Values.service.ports | trim | indent 2 }}
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
